### ISSUE TITLE
Support for `content` attribute?

### ISSUE THREAD

**Issue by jkphl** [jkphl/rdfa-lite#2]
See https://github.com/jkphl/micrometa/pull/14

**Comment by jkphl** [comment]
HTML Microdata became a [W3C Working Draft](https://www.w3.org/TR/microdata/) and still the `content` attribute is no part of the [value retrieval algorithm](https://www.w3.org/TR/microdata/#values). Closing this.

**Comment by 1994rstefan** [comment]
It looks like the W3C Working Draft about microdata has changed and the `content` attribute is now part of the [value retrieval algorithm](https://www.w3.org/TR/microdata/#values).
